### ISSUE TITLE
unable to run demo

### ISSUE THREAD

**Issue by acarl005** [foamliu/Deep-Image-Matting#1]
Hello, I'm trying to run the demo with the pre-trained model. I downloaded it and moved it inside a `models/` directory, but I get this error.

```sh
python demo.py
```

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "demo.py", line 9, in <module>
    from data_generator import generate_trimap, random_choice, get_alpha_test
  File "/Users/andy/Documents/projects/Deep-Image-Matting/data_generator.py", line 17, in <module>
    with open('Combined_Dataset/Training_set/training_fg_names.txt') as f:
IOError: [Errno 2] No such file or directory: 'Combined_Dataset/Training_set/training_fg_names.txt'
```

**Comment by Devin147** [comment]
please contact author for dataset

**Comment by foamliu** [comment]
Devin147 is correct, the demo relies on original dataset.

**Comment by jjlchui** [comment]
Hi foamliu, how can I get the dataset?

**Comment by foamliu** [comment]
Follow the instruction (in README.md) to contact author for the dataset.


在 2018-09-12 12:27:36，"jjlchui" <notifications@github.com> 写道：


Hi foamliu, how can I get the dataset?

**Comment by jjlchui** [comment]
Thanks.  刘杨

**Comment by aigc-boys** [comment]
@jjlchui , Can you send me the Adobe datasets's link, I have send a email for author of Deep Image Matting, but I didn't get a reply.Thanks. My email is 1575262785@qq.com.

**Comment by flyonok** [comment]
@jjlchui , Can you send me the Adobe datasets's link, I have send a email for author of Deep Image Matting, but I didn't get a reply.Thanks. My email is flyonok@163.com

**Comment by syoung125** [comment]
Can you send me the Adobe datasets's link, I have send a email for author of Deep Image Matting, but I didn't get a reply.Thanks. My email is laura120555@gmail.com

**Comment by DexJoke** [comment]
@foamliu Can you send me the Adobe datasets's link, I have send a email for author of Deep Image Matting, but I didn't get a reply.Thanks. My email is dexjokesh@gmail.com

**Comment by foamliu** [comment]
Sorry guys, I am not authorized to redistribute this dataset.

**Comment by sukki37** [comment]
@jjlchui ,  @syoung125  @foamliu  @flyonok Can you send me the Adobe datasets's link, I have send a email for author of Deep Image Matting, but I didn't get a reply.Thanks. My email is 165627230@qq.com.
