### ISSUE TITLE
question about "custom_loss_wrapper"

### ISSUE THREAD

**Issue by liminn** [foamliu/Deep-Image-Matting#10]
Hi，Thanks for sharing your source code! Here is my question:
- There are several lines of code in the **`train_refinement.py`** script：
```Python
from utils import custom_loss_wrapper, get_available_cpus
# ...
refinement.compile(optimizer='nadam', loss=custom_loss_wrapper(refinement.input))
```
- My question: where is the **`custom_loss_wrapper`** function in **`utils.py`** ? It doesn't seem to exist in `utils.py`.

Waiting for your reply, thank you！

**Comment by foamliu** [comment]
It was deleted, please check the git history of "utils.py".
