### ISSUE TITLE
No such file or directory: 'Combined_Dataset/Training_set/training_fg_names.txt'

### ISSUE THREAD

**Issue by yuzhiren** [foamliu/Deep-Image-Matting#12]
I just want to try the demo part, still met with 
"No such file or directory: 'Combined_Dataset/Training_set/training_fg_names.txt'"??

**Comment by fanjianing** [comment]
Same to you.

**Comment by bmetge** [comment]
same here

**Comment by adarshmenon** [comment]
Exactly the same issue. Where do we find the these text files?

**Comment by fanjianing** [comment]
reply all above questions: this file is in Adobe Image Matting Dataset. You have to request the dataset from the author of the paper.

**Comment by aigc-boys** [comment]
@fanjianing ,Can you send me the Adobe datasets's link, I have send a email for author of Deep Image Matting, but I didn't get a reply.Thanks. My email is 1575262785@qq.com.

**Comment by wanlipeng** [comment]
@fanjianing  Have you got the Adobe Image Matting Dataset,Thanks for your reply!!

**Comment by hufangjian** [comment]
I get the same error.

**Comment by foamliu** [comment]
Fanjianing is correct, please contact the author for the dataset.

**Comment by iEdric** [comment]
same here

**Comment by foamliu** [comment]
Again, please contact the author for the dataset.
