### ISSUE TITLE
How to implement the unpool

### ISSUE THREAD

**Issue by zhengyi123456** [foamliu/Deep-Image-Matting#13]
请问您是如何定义unpool的操作的呢，注意到您的unpool操作不是简单的upsample？
还有在decoder阶段，您使用的卷积核的数量没有按照原文当中的来，有没有其他的影响呢

**Comment by zhengyi123456** [comment]
自己回答一下，可以参考FCN网络的设计

**Comment by foamliu** [comment]
unpooling的机制和反卷积部分的实现参考了 SegNet 的论文：https://arxiv.org/pdf/1511.00561.pdf

**Comment by rainsun1** [comment]
upsample就是1对4拷贝填充，unpool需要按pool时的位置，把最大像素按这个位置填充回去，其余填0。我的理解。
