### ISSUE TITLE
No file Adobe_Deep_Matting_Dataset.zip

### ISSUE THREAD

**Issue by niusilong** [foamliu/Deep-Image-Matting#15]
I follow the [instruction](https://sites.google.com/view/deepimagematting) to contact author for the dataset. But had not received the Adobe_Deep_Matting_Dataset.zip dataset file yet. How to get the dataset file now ? 
email: niusilong2006@163.com

**Comment by chenzhaiyu** [comment]
@niusilong Same here. Could you send me one if you have it? My email is contact[AT]chenzhaiyu.com. Thanks.

**Comment by foamliu** [comment]
I am not authorized to share the dataset with anyone else, please contact to the author directly.

**Comment by confident-OH** [comment]
> I follow the [instruction](https://sites.google.com/view/deepimagematting) to contact author for the dataset. But had not received the Adobe_Deep_Matting_Dataset.zip dataset file yet. How to get the dataset file now ?
> email: [niusilong2006@163.com](mailto:niusilong2006@163.com)

如果你拿到了Adobe_Deep_Matting_Dataset.zip，能发我一份吗？现在急需这个数据集，但作者出差了，我的邮箱confidentoh@foxmail.com

**Comment by liuzimo** [comment]
May I have a copy, thank you very much
 spiritai@qq.com
 or
 spiritgufy@gmail.com

**Comment by codingdudecom** [comment]
I don't suppose there's any chance of getting a copy of that. If there is, please send me a download link at admin@coding-dude.com
