### ISSUE TITLE
Test.py model not found

### ISSUE THREAD

**Issue by oee5215** [foamliu/Deep-Image-Matting#17]
Hi foamliu,

I've been having some errors implementing the test.py. The code requires a model named model.35-0.03.hdf5, which is not available in your repository. I tried using the model for the demo.py, but it says that I'm "trying to load a weight file containing 33 layers into a model with 26 layers". Could you please upload the correct model file? 

Best,

Oscar

**Comment by oee5215** [comment]
so it ended up working with the model for the demo.py after I modified the code to include the build_refinement step, as shown in the demo.

**Comment by chenzhaiyu** [comment]
Hi iee5215,
Could you send me the Adobe dataset if you have it? I contacted Mr. Price but haven't received any response yet. My email is contact[AT]chenzhaiyu.com, Thanks! @oee5215

**Comment by oee5215** [comment]
Hi @realczy. Unfortunately, I can't since part of the agreement is that we can't openly share the dataset with other parties. Sorry about that, hope he replies soon!
