### ISSUE TITLE
Can we test on arbitrary size images?

### ISSUE THREAD

**Issue by oee5215** [foamliu/Deep-Image-Matting#18]
I noticed that test.py assumes that the input image size is 320 x 320 pixels.  How can I test on an arbitrary image size without the need for cropping or resizing before inputting it into the model?

**Comment by foamliu** [comment]
We cannot.

**Comment by cardwing** [comment]
@oee5215, just modify the shape of the input tensor to be (None, None, 4) and re-train the model. In this condition, the model can handle inputs with arbitrary sizes. 

Edit:
After following the above suggestions, it seems that this method does not work. I will test other options and see if it can use inputs with arbitrary sizes.

**Comment by oee5215** [comment]
@cardwing Thank you! Please let me know if you find a working solution, since it would be ideal to use this model for my research project.

**Comment by cardwing** [comment]
@oee5215, the pytorch version of deep-image-matting (https://github.com/huochaitiantang/pytorch-deep-image-matting) is preferred and yields better performance.
