### ISSUE TITLE
StopIteration: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by wangxin1233** [foamliu/Deep-Image-Matting#21]
![image](https://user-images.githubusercontent.com/44840625/50747933-944a1c00-1271-11e9-9182-6d53b0fca9f5.png)
could you help me  to sovel the problem?thanks

**Comment by babyformula** [comment]
Normally it's because of the wrong data path or loading method

**Comment by foamliu** [comment]
Just tried and train.py works, so seems this is an incorrect data path issue.
