### ISSUE TITLE
Training is very slow with GPU utility

### ISSUE THREAD

**Issue by haichaoyu** [foamliu/Deep-Image-Matting#27]
Hello Yang,

Thanks for your efforts to implement this. I found training process is quite slow and GPU util percent is quite low (0% during a large portion of each iteration). Is this the same case in your training?

BTW, can this code reproduce the claimed performance in the paper?

Thanks

**Comment by qianbin228** [comment]
@haichaoyu  You must get something wrong. When I run the demo, the GPU util percent is normal.

**Comment by HWNHJJ** [comment]
您好~     我已学习过基础知识，仔细阅读了论文。现在毕设需要复现实验，老师让我试运行这段代码。但我不知道如何运行起来，请问您能指导一二吗。
相关环境配置我已经弄好。

**Comment by Ruifeng-Zhou24** [comment]
@haichaoyu 
hi, 

I encountered the same problem as yours. Have you solved your problem and could you share your solution?

thanks

**Comment by foamliu** [comment]
Maybe you'd like to check out this project: https://github.com/foamliu/Deep-Image-Matting-PyTorch.

**Comment by haichaoyu** [comment]
Hi @Ruifeng-Zhou24 ,

Finally I implemented my own training framework. I have no idea why it is slow yet. Maybe because the pre-processing is too slow. If yes, maybe you can try some data prefetching methods like [this](https://github.com/Yaoyi-Li/GCA-Matting/blob/master/main.py#L62).

**Comment by Ruifeng-Zhou24** [comment]
I will take a look at that, thanks again @haichaoyu @foamliu
