### ISSUE TITLE
how  to  run  this  project?

### ISSUE THREAD

**Issue by HWNHJJ** [foamliu/Deep-Image-Matting#28]
i can not   run  the  project.what should  i   do?
when  i    run  pre_process.py  ,it  will show  " No module named 'tqdm' "

**Comment by farazBhatti** [comment]
for python 2
pip install tqdm

for python 3
pip3 install tqdm

this module is used for showing progress bar

**Comment by HWNHJJ** [comment]
@farazBhatti   thanks
