### ISSUE TITLE
some  error

### ISSUE THREAD

**Issue by HWNHJJ** [foamliu/Deep-Image-Matting#29]
When   i    run   the     test.py,  it   show:  
OSError: Unable to open file (Unable to open file: name = 'models/final.42-0.0398.hdf5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)

but   i  had   put  the final.42-0.0398.hdf5   in this folder.

**Comment by foamliu** [comment]
Please have a double check, feel free to reactivate this issue you're sure this is a code issue.
