### ISSUE TITLE
recreate datasets after each epoch

### ISSUE THREAD

**Issue by tsing90** [foamliu/Deep-Image-Matting#31]
@foamliu Hi, thanks for your implementation of that paper. In that paper, it was said :

" Finally, the training inputs are recreated randomly after each training epoch."(in 4.1 - implementation part)

in your code (https://github.com/foamliu/Deep-Image-Matting/blob/master/data_generator.py#L156), you just did a shuffle of your name list, without recreating (recomposting) the input images. I think this would be an essential reason that your train model cannot achieve that paper's results, am I right?

cheers

**Comment by foamliu** [comment]
Recreating dataset is super time-consuming, please have a try and let us know if you see improvement.
