### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by HWNHJJ** [foamliu/Deep-Image-Matting#33]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by HWNHJJ** [comment]
I   find   the   answers.  thanks

**Comment by yeshwanth28** [comment]
> I find the answers. thanks
Can you tell me how to resolve this error I am also having same error while executing  ?
Please help me with this

**Comment by foamliu** [comment]
This error usually means the image path is incorrect.
