### ISSUE TITLE
Is there a difference in the architecture?

### ISSUE THREAD

**Issue by VolzotanSmeik** [foamliu/Deep-Image-Matting#34]
Thanks for sharing your code! 
I have two questions regarding it, it would be nice if someone could help me out a bit:

1) You added skip connections (which I couldn't find in the description in the original "Deep Image Matting" adobe paper) to the encoder-decoder network and removed/commented the (1x1x4096) convolution in the model.py, why is that?

2) Why did you define for training a different model (in segnet.py) than for testing (demo.py uses modle.py and train.py uses segnet.py)? Also the segnet.py model version has no convolution operation between the last maxpooling operation of the encoder and the first upsampling operation of the decoder, and thus the first convolution operation receives a concatenation of the same input, except that one version is "blurred"...?

Could it be that these changes lead to better results? If yes it would be nice if you could share some metrics :)

**Comment by foamliu** [comment]
Hi @VolzotanSmeik, nice to meet you. 
The skip connections structure (pooling indices) and removal of fully connected layers are inspired by SegNet paper (https://arxiv.org/pdf/1511.00561.pdf). It reduces the number of parameters significantly (from 134M to 14.7M), made the net easier to train.
