### ISSUE TITLE
vgg16

### ISSUE THREAD

**Issue by wangxin1233** [foamliu/Deep-Image-Matting#36]
Thank you very much for sharing the code. I have two questions to ask and hope to get your reply:

During the training, VGG16 was selected for the pre-training model, but where did you import the VGG16 model?

In addition, if I want to follow up the final.42-0.0398.hdf5 you gave me and continue the training, where should I import this weight?

**Comment by foamliu** [comment]
You can find the pretrained VGG weights from Keras's website @ https://keras.io/applications/.
