### ISSUE TITLE
Doubt about alpha and trimap

### ISSUE THREAD

**Issue by wangxin1233** [foamliu/Deep-Image-Matting#38]
首先，非常感谢您提供了代码实现了这篇论文。关于最后的结果我有一些疑问。
我们这篇文章的输入虽然是trimap，但是trimap的输入依赖于alpha.也就是说首先我们必须提供alpha，是这个意思吗？
最后的输出结果out的损失是和提供的alpha对比吗？也就是代码中的真实值其实就是我们提供的alpha吗？
First of all, thank you very much for providing the code to implement this paper. I have some questions about the final result.

The input of this article is trimap, but the input of trimap depends on alpha. Is the loss of the final output out compared to the provided alpha? Is the GT in the code actually the alpha that we provide?

**Comment by foamliu** [comment]
Please refer to the paper.

**Comment by cians** [comment]
because the trimap for each image is randomly dilated from its ground truth alpha matte .......

**Comment by FantasyJXF** [comment]
> because the trimap for each image is randomly dilated from its ground truth alpha matte .......

I think the most important thing to matiing with this model is to get the trimap, which I think it's so hard to get. How did you do this?
