### ISSUE TITLE
Noisy output

### ISSUE THREAD

**Issue by w1ldm1nd** [foamliu/Deep-Image-Matting#41]
Hello, first of all I want to thank @foamliu for the implementation, it was a huge help for training and testing this network.

However I have problem with noisy matte as output. My output mask looks like this (white and gray pixels outside object area, sometimes black and grey pixels inside object as well):

![jennifer_lawrence_resized](https://user-images.githubusercontent.com/50505479/57563701-74ef0700-73a9-11e9-8106-07697ebaddea.jpg)

No matter which weights I'm using - provided by you or retrained by me. It seems that noise came from the border around uncertain (gray) area on trimap:

![jennifer_lawrence](https://user-images.githubusercontent.com/50505479/57563711-8fc17b80-73a9-11e9-850f-e0e7ec07b993.jpg)

Does anyone have any idea what the problem might be?

**Comment by peachthiefmedia** [comment]
I've found the problem is in the trimap, if you use a index colour mode with values of only 0,128,255 it doesn't show the edge.  I did this by posterising the trimap in photoshop, but its easiest to copy the trimaps in the alphamatting database.

**Comment by foamliu** [comment]
This version does not work well with different size, please take a look at v2 @ https://github.com/foamliu/Deep-Image-Matting-v2.
