### ISSUE TITLE
Failed to get convolution algorithm

### ISSUE THREAD

**Issue by Rimander** [foamliu/Deep-Image-Matting#42]
When execute "python demo.py"
Tensorflow-gpu - 1.13
But working with tensorflow cpu

Crash on -> y_pred = final.predict(x_test)

tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv1_1/convolution}}]]

**Comment by foamliu** [comment]
Close this since it seems an environment issue.
