### ISSUE TITLE
 loss computational error

### ISSUE THREAD

**Issue by wy3406** [foamliu/Deep-Image-Matting#43]
Hi，Thanks for sharing your source code! Here is my question:
K.sum(K.sqrt(K.square(diff) + epsilon_sqr)) / (num_pixels + epsilon) is equal to （diff_1+diff_2+..+diff_n）/（mask_1+mask_2+...+diff_n) is it right?
but I think the real way to do this is [(diff_1/mask_1)+(diff_2/mask_2)+..+(diff_n/mask_n)]/n

**Comment by foamliu** [comment]
The entire function is this:
`def alpha_prediction_loss(y_true, y_pred):
    mask = y_true[:, :, :, 1]
    diff = y_pred[:, :, :, 0] - y_true[:, :, :, 0]
    diff = diff * mask
    num_pixels = K.sum(mask)
    return K.sum(K.sqrt(K.square(diff) + epsilon_sqr)) / (num_pixels + epsilon)`

Why do you think the approach described above is the real way?
