### ISSUE TITLE
Ask for metrics code

### ISSUE THREAD

**Issue by shellin-star** [foamliu/Deep-Image-Matting#48]
Hello, 
sorry for bothering
recently, I am confused about the matting metrics like 'SAD' and 'MSE', 'Gradient' , 'Connectivity' , do you have codes for that? It would be great help to me. Thanks~

**Comment by devvikas** [comment]
its here:
 https://github.com/foamliu/Deep-Image-Matting/blob/master/utils.py

**Comment by shellin-star** [comment]
Thank you for your reply!
In this file, I see 'SAD'and 'MSE'. Can you provide code about 'Gradient' and 'Conenctivity'?
Thank you agin~

**Comment by foamliu** [comment]
It is not done yet, please feel free to create a PR for this.

**Comment by Jason-xin** [comment]
> Thank you for your reply!
> In this file, I see 'SAD'and 'MSE'. Can you provide code about 'Gradient' and 'Conenctivity'?
> Thank you agin~

Hello, have you solved this problem? I also don't know how to code this two metrics

**Comment by Datura0822** [comment]
I need too.

**Comment by RaymondJiangkw** [comment]
Hi, 
I think you can find them here.
[https://github.com/JizhiziLi/GFM/blob/master/core/evaluate.py](https://github.com/JizhiziLi/GFM/blob/master/core/evaluate.py)
