### ISSUE TITLE
How can we train on higher resolution images ?

### ISSUE THREAD

**Issue by devvikas** [foamliu/Deep-Image-Matting#49]
My training images are of 1200 * 800 resolution. How can i train using your pre trained model ?

**Comment by foamliu** [comment]
Please take a look at https://github.com/foamliu/Deep-Image-Matting-v2.

**Comment by devvikas** [comment]
I am using this repo for training on my custom dataset. I am using your pretrained model in my training.
I get following values. 

loss: 2.3741e-06 
acc: 0.4070

loss becomes very low quickly. Is this correct ? or is there any other way to check if my training is going fine ?
