### ISSUE TITLE
How to test on my own dataset?

### ISSUE THREAD

**Issue by visonpon** [foamliu/Deep-Image-Matting#5]
Hi,
As I see, both the` demo.py `and `test.py` use the trimap to output the results:

` trimap = generate_trimap(alpha)`---demo.py(it seems trimap generated from ground truth)
` ap.add_argument("-t", "--trimap", help="path to the trimap file")`---test.py(load from existed file)
so, how to get the trimap of my own dataset and test on the pretrained model?
thanks~

**Comment by foamliu** [comment]
Semantic-segmentation? E.g. if foreground is person this project may help: https://github.com/foamliu/Look-Into-Person

**Comment by visonpon** [comment]
Hi
foamliu, thanks for your quickly response, but the pretrained model provided by the project [https://github.com/foamliu/Look-Into-Person](url) do not match the model.  Someone has mentioned the load error, hope you can help us~ thanks~
