### ISSUE TITLE
dataset request

### ISSUE THREAD

**Issue by TClan8023** [foamliu/Deep-Image-Matting#57]
Hi,
   I'm doing research on image matting based on trimap-free method. Would you mind shaing the datasets with me? My email is 1094859220@qq.com. Thanks a lot and Look forward to your reply.

**Comment by foamliu** [comment]
I was not authorized to redistribute it.



---- Replied Message ----
| From | Xiaolan ***@***.***> |
| Date | 01/31/2023 14:18 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [foamliu/Deep-Image-Matting] dataset request (Issue #57) |

Hi,
I'm doing research on image matting based on trimap-free method. Would you mind shaing the datasets with me? My email is ***@***.*** Thanks a lot and Look forward to your reply.
