### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by shliang0603** [foamliu/Deep-Image-Matting#6]
@foamliu-ms 
when I run pre-process.py ,report the error:FileNotFoundError: [Errno 2] No such file or directory: 'Adobe_Deep_Matting_Dataset.zip'. Where can I download this data set of "Adobe_Deep_Matting_Dataset.zip"
![image](https://user-images.githubusercontent.com/37186266/47211615-85697100-d3c8-11e8-8411-23d6003dfa51.png)

 when I run demo.py ,report a error: FileNotFoundError: [Errno 2] No such file or directory: 'Combined_Dataset/Training_set/training_fg_names.txt'  , I don't know where to find the "training_fg_name.txt" file. In my download Training_set dir don't have "training_fg_names.txt" file.
![image](https://user-images.githubusercontent.com/37186266/47211076-31aa5800-d3c7-11e8-8f4a-32902d0c831d.png)
Can you help me ? Thanks

**Comment by bobykhani** [comment]
I think you should contact paper's Author For the dataset and download that into your project's Folder.
for Demo you should download pretrained model from https://github.com/foamliu/Deep-Image-Matting/releases/download/v1.0/final.42-0.0398.hdf5 and put that into models folder in the root of the project

**Comment by shliang0603** [comment]
@bobykhani Thanks for your reply，I have contacted the second author of the paper , but haven't received his reply. Do you have the "Adobe_Deep_Matting_Dataset.zip" ?

**Comment by shliang0603** [comment]
Thanks for your answer, I have downloaded the pre-trained model in model
directory of project. Now I am applying the data set to author, but no
reply has been received.

bobykhani <notifications@github.com> 于2018年10月22日周一 上午6:45写道：

**Comment by foamliu** [comment]
Close the issue.

**Comment by aigc-boys** [comment]
@bobykhani ,@ shliang0603 , Can you send me the Adobe datasets's link, I have send a email for author of Deep Image Matting, but I didn't get a reply.Thanks. My email is 1575262785@qq.com.

**Comment by albalab** [comment]
@bobykhani, @shliang0603,  @18191171661 

Hey guys!
Please, can you send me the Adobe datasets's link. I have send a email for author of Deep Image Matting, but didn't get a reply. Thanks.

My email amenothis@gmail.com.

**Comment by flyfish01** [comment]
@bobykhani, @shliang0603, @18191171661 @albalab 
Hi, guys!
  Do you received the dataset's link, could you share it, thank you!
  My email is haoran.andy###gmail.com

**Comment by apoorva1225** [comment]
Hi, @bobykhani, @shliang0603 , @flyfish01 
Can anyone of you help me with this dataset. I emailed the authors but haven't received any reply. Thank you.
My email is apoorva1225@gmail.com
