### ISSUE TITLE
question about "compositional_loss"

### ISSUE THREAD

**Issue by liminn** [foamliu/Deep-Image-Matting#9]
Hi，Thanks for sharing your source code! Here is my question:
First,  `data_generator.py` will generate `batch_y`. The shape of `batch_y` is  `(batch, img_rows, img_cols, 2)`.
Second, `compositional_loss(y_true, y_pred)` function  defined in the `utils.py`:
```Python
def compositional_loss(y_true, y_pred):
    #...
    image = y_true[:, :, :, 2:5]
    fg = y_true[:, :, :, 5:8]
    bg = y_true[:, :, :, 8:11]
    #...
```

- My understanding is that the generated `batch_y`  corresponds to `y_true`
- `batch_y` only has 2 channels in the fourth dimension.
- My quesion: for the code **`y_true[:, :, :, 2:5]`** or  **`y_true[:, :, :, 5:8]`** or **` y_true[:, :, :, 8:11]`**. **Why can I access the channels greater than 2 in the fourth dimension of `y_true`**?
- My understanding is that I can only do such operations, such as **`y_true[:, :, :, 0]`** or **`y_true[:, :, :, 1]`**.

Waiting for your reply, thank you！

**Comment by mathrho** [comment]
had the same concern!

**Comment by xaibeing** [comment]
Same question! 
But the code worked without error.
Do you figure this out? @liminn @mathrho

**Comment by liminn** [comment]
@xaibeing Try:
```
>>>a = np.zeros((2,2,2))
>>>a[:,:,0]      # good
>>>a[:,:,2]      # error
>>>a[:,:,10:20]  # not a error, return : array([], shape=(2, 2, 0), dtype=float64)
```

**Comment by xaibeing** [comment]
@liminn thanks! you are right, I didn't know array can be used this way.
And a[:,:,10:20]  return array[], so I think the compositional_loss didn't take effect, unless fill batch_y with image, fg and bg. right?

**Comment by liminn** [comment]
@xaibeing Yes, but maybe the compositional_loss isn't important ^_^

**Comment by tsing90** [comment]
I found the same issue, interesting bug, LOL!
And it seems that cropped image/alpha/trimap are not resized to 320x320 ......
